spring:
  application:
    name: '@pom.name@'
  profiles:
    #设定默认激活的profile
    active: local
security:
  basic:
    #禁用springboot安全
    enabled: false

logging:
  #logback配置文件
  config: classpath:logback-spring.xml
  #日志文件名称
  file: '@pom.name@'
  #日志文件路径
  path: '/xs/logs/@pom.name@/'
  #日志文件级别（在bootstrap文件中可以配置默认值，可以在application.yml中进行覆盖，或是在执行的profile配置中覆盖）
  #注意：不要修改此处配置，如果想修改执行环境的日志级别，可修改执行profile中的日志级别，覆盖此默认配置
  #可选配置：TRACE, DEBUG, INFO, WARN, ERROR, FATAL, OFF
  level:
    root: INFO

#项目信息，用info做前缀的配置将在admin管理后台中进行显示，属性可以自己定义没有强制要求，例如可以设置info.contact.email
info:
  build:
    name: '@pom.name@'
    description: '@pom.description@'
    version: '@pom.version@'


server:
  port: 9901
---
spring:
  profiles: local
